# -------------------------------------
# Be careful modifying this ...
# -------------------------------------

# This is the language to use for lodestone
lodestone_language: eu

# This is the parse method, the accepted methods are:
# 1 - curl (http://php.net/manual/en/book.curl.php)
# 2 - file_get_contents (http://php.net/manual/en/function.file-get-contents.php)
parse_method: 1